if(EXISTS "/home/rafaelgss/repos/sfml-imgui-foot/test/tests_tests-4c0d252.cmake")
  include("/home/rafaelgss/repos/sfml-imgui-foot/test/tests_tests-4c0d252.cmake")
else()
  add_test(tests_NOT_BUILT-4c0d252 tests_NOT_BUILT-4c0d252)
endif()
